const OBSERVATIONS=['gc1','chaos1','gc2','chaos2','gc3'];
const state={gc1:{truth:null,pattern:null,timing:null},chaos1:{truth:null,mechanic:null},gc2:{truth:null,pattern:null},chaos2:{truth:null,mechanic:null},gc3:{debuff:null,beamTruth:null},thunder:{truth:null},blizzard:{truth:null},magicout:{thunderTruth:null,blizzardTruth:null},currentStep:1,editing:null,finished:false};
const patterns={water:['水圧縮','i-water'],lightning:['雷','i-lightning'],accel:['加速度のみ','i-accel'],gaze:['加速＋呪詛','i-gaze']};
const names={gc1:'GC①',chaos1:'カオス①',gc2:'GC②',chaos2:'カオス②',gc3:'GC③'};
const choice=(value,label,cls='')=>`<button class="choice ${cls}" data-value="${value}">${label}</button>`;
const truthChoices=()=>choice('true','<span class="mark"></span>真','true')+choice('false','<span class="mark">?</span>偽','false');
const patternChoices=keys=>keys.map(k=>choice(k,`<span class="game-icon ${patterns[k][1]}"></span>${patterns[k][0]}`)).join('');
const group=(label,html,key)=>`<div class="group" data-key="${key}"><span class="group-label">${label}</span><div class="choices">${html}</div></div>`;

function complete(id){const s=state[id];if(id==='gc1')return s.truth!==null&&s.pattern&&(!['water','lightning'].includes(s.pattern)||s.timing);if(id==='chaos1')return s.truth!==null&&s.mechanic;if(id==='gc2')return s.truth!==null&&s.pattern;if(id==='chaos2')return s.truth!==null&&s.mechanic;if(id==='gc3')return s.debuff&&s.beamTruth!==null;return false;}
const preComplete=()=>OBSERVATIONS.every(complete);
function body(id){
  if(id==='gc1')return group('真偽',truthChoices(),'truth')+group('自分のデバフ',patternChoices(Object.keys(patterns)),'pattern')+(['water','lightning'].includes(state.gc1.pattern)?group('秒数を見て判断',choice('early','早')+choice('late','遅'),'timing'):'');
  if(id==='gc2'){const keys=['water','lightning'].includes(state.gc1.pattern)?['accel','gaze']:['water','lightning'],t=timingFor(state.gc2,'gc2');return group('真偽',truthChoices(),'truth')+group('自分のデバフ',patternChoices(keys),'pattern')+(state.gc2.pattern?`<div class="group"><div class="auto">${t==='early'?'早':'遅'}処理（GC①から自動）</div></div>`:'');}
  if(id==='chaos1')return group('真偽',truthChoices(),'truth')+group('付与された属性',choice('fire','<span class="game-icon i-fire"></span>ほのお')+choice('wave','<span class="game-icon i-wave"></span>つなみ'),'mechanic');
  if(id==='chaos2')return group('真偽',truthChoices(),'truth')+`<div class="group"><span class="group-label">属性</span><div class="auto">${state.chaos2.mechanic==='fire'?'ほのお':'つなみ'}（自動）</div></div>`;
  return group('自分のデバフ',choice('allagan','アラガンフィールド')+choice('transcendence','死の超越'),'debuff')+group('ビームの真偽',truthChoices(),'beamTruth');
}
function renderInputs(){const active=OBSERVATIONS.findIndex(id=>!complete(id)),done=OBSERVATIONS.filter(complete).length;document.querySelector('#progress').textContent=preComplete()?'事前入力 完了':`${done} / ${OBSERVATIONS.length}`;document.querySelector('.input-panel').classList.toggle('ready',preComplete());document.querySelector('#inputs').innerHTML=OBSERVATIONS.map((id,i)=>{const ok=complete(id),open=state.editing===id||(!ok&&i===active),locked=i>active&&!ok;return `<article class="input-stage ${ok?'complete':''} ${open?'open':''} ${locked?'locked':''}" data-stage="${id}"><button class="stage-title" ${locked?'disabled':''}><span class="num">${ok?'✓':i+1}</span><strong>${names[id]}</strong><small>${ok?'入力済み':open?'← 今ここ':''}</small></button><div class="stage-body">${body(id)}</div></article>`}).join('');document.querySelectorAll('.input-stage').forEach(el=>el.querySelectorAll('.choice').forEach(b=>{const key=b.closest('[data-key]').dataset.key;b.classList.toggle('selected',String(state[el.dataset.stage][key])===b.dataset.value)}));}
function chooseObservation(stage,key,value){state[stage][key]=value==='true'?true:value==='false'?false:value;if(stage==='gc1'&&key==='pattern'){state.gc1.timing=null;state.gc2.pattern=null;}if(stage==='chaos1'&&key==='mechanic')state.chaos2.mechanic=value==='fire'?'wave':'fire';if(complete(stage))state.editing=null;render();}
function timingFor(gc,id){if(gc.pattern==='gaze')return id==='gc1'?'early':'late';if(gc.pattern==='accel')return id==='gc1'?'late':'early';if(id==='gc1')return gc.timing;const first=timingFor(state.gc1,'gc1');return first==='early'?'late':first==='late'?'early':null;}

// Input -> parsed debuffs. Assignment source and execution step stay separate.
function parseDebuffs(){const out=[];for(const id of ['gc1','gc2']){const gc=state[id],timing=timingFor(gc,id);if(!complete(id)||!timing)continue;if(['water','lightning'].includes(gc.pattern))out.push({source:id,type:gc.pattern,truthValue:gc.truth,timing,targetStep:timing==='early'?2:6});else{out.push({source:id,type:'acceleration',truthValue:gc.truth,timing,targetStep:timing==='early'?2:6});if(gc.pattern==='gaze')out.push({source:id,type:'gaze',truthValue:gc.truth,timing,targetStep:timing==='early'?3:7});}}
  for(const id of ['chaos1','chaos2'])if(complete(id))out.push({source:id,type:state[id].mechanic,truthValue:state[id].truth,timing:state[id].mechanic==='fire'?'early':'late',targetStep:state[id].mechanic==='fire'?4:8});
  if(complete('gc3'))out.push({source:'gc3',type:state.gc3.debuff,truthValue:state.gc3.beamTruth,timing:'immediate',targetStep:1});return out;}
function gcAction(d){if(!d)return {type:'stack',label:'北へ集合',sub:'TH頭割り'};const spread=(d.type==='lightning')===d.truthValue;return {type:spread?'spread':'stack',label:spread?(d.timing==='early'?'北東 or 北西':'西'):'北へ集合',sub:spread?'TH散開':'TH頭割り'};}
function accelAction(d){return d?{type:d.truthValue?'stop':'move',label:d.truthValue?'止まる':'動く',sub:'加速度'}:{type:'none',label:'加速度なし',sub:'固定処理'};}
const gazeAction=(truth,order)=>({type:truth?'away':'look',label:truth?'見ない':'見る',sub:`視線${order}`});
function chaosAction(d){if(!d)return null;const donut=d.type==='fire'?!d.truthValue:d.truthValue;return {type:donut?'donut':'circle',label:donut?'ドーナツの中':'円から離れる',sub:d.type==='fire'?'ほのお':'つなみ'};}
function beamAction(){if(!complete('gc3'))return null;const same=state.gc3.debuff==='transcendence'?state.gc3.beamTruth:!state.gc3.beamTruth;return {type:'beam',label:same?'同じ色のビーム':'違う色のビーム',sub:state.gc3.debuff==='allagan'?'アラガン':'死の超越'};}
function floorAction(kind,truth,final=false){if(truth===null)return null;return {type:kind,label:kind==='thunder'?(truth?'直線を踏まない':'直線を踏む'):(truth?'扇を踏まない':'扇を踏む'),sub:`${final?'最終':''}${kind==='thunder'?'サンダガ':'ブリザガ'}`};}
const step=(no,name,confirmed,actions)=>({no,name,status:confirmed?'confirmed':'pending',actions:confirmed?actions.filter(Boolean):[]});
function magicOutActions(){if(state.magicout.thunderTruth===null||state.magicout.blizzardTruth===null)return[];return [floorAction('thunder',state.thunder.truth===state.magicout.thunderTruth,true),floorAction('blizzard',state.blizzard.truth===state.magicout.blizzardTruth,true)];}
function buildTimeline(){const ds=parseDebuffs(),at=n=>ds.filter(d=>d.targetStep===n),element=n=>at(n).find(d=>['water','lightning'].includes(d.type)),accel=n=>at(n).find(d=>d.type==='acceleration'),chaos=n=>chaosAction(at(n).find(d=>['fire','wave'].includes(d.type)));return [
  step(1,'無の氾濫＋ビーム',complete('gc3'),[beamAction()]),step(2,'散開／頭割り①＋早い加速度',complete('gc1')&&complete('gc2'),[gcAction(element(2)),accelAction(accel(2))]),step(3,'サンダガ床＋視線①',state.thunder.truth!==null,[floorAction('thunder',state.thunder.truth),gazeAction(state.gc1.truth,1)]),step(4,'ほのお',!!at(4).length,[chaos(4)]),step(5,'どきどきアルテマ',true,[{type:'ultima',label:'固定処理',sub:'PTの軽減設定に従う'}]),step(6,'散開／頭割り②＋遅い加速度＋ブリザガ',state.blizzard.truth!==null,[gcAction(element(6)),accelAction(accel(6)),floorAction('blizzard',state.blizzard.truth)]),step(7,'視線②',state.gc2.truth!==null,[gazeAction(state.gc2.truth,2)]),step(8,'つなみ',!!at(8).length,[chaos(8)]),step(9,'マジックアウト',state.thunder.truth!==null&&state.blizzard.truth!==null&&state.magicout.thunderTruth!==null&&state.magicout.blizzardTruth!==null,magicOutActions())];}

function icon(type){const me='<circle cx="50" cy="52" r="8" fill="#29bee7" stroke="white" stroke-width="3"/>';if(type==='stop')return `<svg viewBox="0 0 100 100"><text x="50" y="42" text-anchor="middle" font-size="25">✋</text>${me}</svg>`;if(type==='move'||type==='circle')return `<svg viewBox="0 0 100 100">${me}<path d="M60 53h28L77 43m11 10L77 63" stroke="#4ee8ff" stroke-width="6" fill="none"/></svg>`;if(type==='away'||type==='look')return `<svg viewBox="0 0 100 100"><text x="50" y="28" text-anchor="middle" font-size="20">👁</text>${me}<path d="M50 43V${type==='look'?30:82}" stroke="#4ee8ff" stroke-width="5"/></svg>`;if(type==='donut')return `<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="35" fill="none" stroke="#ff5e68" stroke-width="15"/>${me}</svg>`;if(type==='stack'||type==='spread')return `<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="38" fill="#0b1119" stroke="#65758b"/>${me}${type==='spread'?'<circle cx="25" cy="25" r="5" fill="#9aa7b8"/><circle cx="75" cy="25" r="5" fill="#9aa7b8"/><circle cx="25" cy="75" r="5" fill="#9aa7b8"/><circle cx="75" cy="75" r="5" fill="#9aa7b8"/>':'<circle cx="40" cy="42" r="5" fill="#9aa7b8"/><circle cx="60" cy="42" r="5" fill="#9aa7b8"/>'}</svg>`;const emoji={beam:'✦',thunder:'⚡',blizzard:'❄',ultima:'◆',none:'—'}[type]||'●';return `<svg viewBox="0 0 100 100"><text x="50" y="65" text-anchor="middle" font-size="42">${emoji}</text></svg>`;}
const actionHtml=a=>`<div class="action">${icon(a.type)}<div><strong>${a.label}</strong><small>${a.sub}</small></div></div>`;
function observePrompt(stepNo){if(stepNo===3&&state.thunder.truth===null)return liveTruth('サンダガの真偽を確認','thunderTruth');if(stepNo===6&&state.blizzard.truth===null)return liveTruth('ブリザガの真偽を確認','blizzardTruth');if(stepNo===9&&(state.thunder.truth===null||state.blizzard.truth===null))return '<div class="runner-observe"><h3>STEP3・STEP6のチャージ真偽が未入力です</h3></div>';if(stepNo===9&&state.magicout.thunderTruth===null)return liveTruth('アウト・サンダガの真偽を確認','outThunder');if(stepNo===9&&state.magicout.blizzardTruth===null)return liveTruth('アウト・ブリザガの真偽を確認','outBlizzard');return '';
}
const liveTruth=(title,key)=>`<div class="runner-observe"><h3>OBSERVE｜${title}</h3><div class="choices"><button class="choice true" data-live-key="${key}" data-value="true"><span class="mark"></span>真</button><button class="choice false" data-live-key="${key}" data-value="false"><span class="mark">?</span>偽</button></div></div>`;
function renderRunner(steps){const runner=document.querySelector('#runner'),badge=document.querySelector('#phaseBadge');if(!preComplete()){badge.textContent='事前入力中';badge.className='phase-badge';runner.className='runner waiting';runner.innerHTML='<span class="runner-label">PREPARE</span><h2>GC③まで入力してください</h2><p>完了するとSTEP1から実戦ランナーが開始します。</p>';return}if(state.finished){badge.textContent='COMPLETE';badge.className='phase-badge live';runner.className='runner complete';runner.innerHTML='<span class="runner-label">COMPLETE</span><h2>P4処理完了</h2><p>次のトライは右上のRESETから開始できます。</p>';return}badge.textContent=`STEP ${state.currentStep} / 9`;badge.className='phase-badge live';const now=steps[state.currentStep-1],next=steps[state.currentStep],prompt=observePrompt(now.no),ready=now.status==='confirmed';runner.className='runner';runner.innerHTML=`<span class="runner-label">NOW｜STEP ${now.no}</span><h2>${now.name}</h2>${prompt}<div class="runner-actions">${ready?now.actions.map(actionHtml).join(''):'<span class="pending-msg">真偽を入力すると行動を表示</span>'}</div><div class="runner-controls"><button data-runner="back" ${now.no===1?'disabled':''}>← 戻る</button><button class="advance" data-runner="advance" ${!ready?'disabled':''}>${now.no===9?'P4処理完了':'処理完了 →'}</button></div>${next?`<div class="next-preview"><b>NEXT｜STEP ${next.no}</b>　${next.name}</div>`:''}`;}
function renderTimeline(steps){document.querySelector('#timeline').innerHTML=steps.map(s=>`<article class="step ${s.status} ${state.currentStep===s.no?'current':''} ${state.currentStep+1===s.no?'next':''} ${s.no<state.currentStep?'past':''}" data-step="${s.no}"><div class="step-no">STEP<b>${s.no}</b></div><div class="step-info"><h2>${s.name}</h2><span class="status">${s.status==='confirmed'?'確定':'判定待ち'}</span></div><div class="actions">${s.status==='pending'?'<span class="pending-msg">判定待ち</span>':s.actions.map(actionHtml).join('')}</div></article>`).join('');}
function render(){renderInputs();const steps=buildTimeline();renderRunner(steps);renderTimeline(steps);}
function chooseLive(key,value){const truth=value==='true';if(key==='thunderTruth')state.thunder.truth=truth;if(key==='blizzardTruth')state.blizzard.truth=truth;if(key==='outThunder')state.magicout.thunderTruth=truth;if(key==='outBlizzard')state.magicout.blizzardTruth=truth;render();}
function reset(){for(const id of OBSERVATIONS)for(const key of Object.keys(state[id]))state[id][key]=null;state.thunder.truth=null;state.blizzard.truth=null;state.magicout.thunderTruth=null;state.magicout.blizzardTruth=null;state.currentStep=1;state.editing=null;state.finished=false;render();}
function selfTest(){console.assert(buildTimeline().length===9);console.assert(gcAction({type:'lightning',truthValue:true,timing:'early'}).type==='spread');console.assert(gcAction({type:'water',truthValue:false,timing:'late'}).type==='spread');}
selfTest();
if(typeof document!=='undefined'){document.addEventListener('click',e=>{const live=e.target.closest('[data-live-key]');if(live)return chooseLive(live.dataset.liveKey,live.dataset.value);const c=e.target.closest('.input-stage .choice');if(c){const stage=c.closest('.input-stage').dataset.stage,key=c.closest('[data-key]').dataset.key;return chooseObservation(stage,key,c.dataset.value)}const title=e.target.closest('.stage-title');if(title&&!title.disabled){const id=title.closest('.input-stage').dataset.stage;state.editing=state.editing===id?null:id;return render()}const control=e.target.closest('[data-runner]');if(control){if(control.dataset.runner==='back')state.currentStep=Math.max(1,state.currentStep-1);else if(buildTimeline()[state.currentStep-1].status==='confirmed'){if(state.currentStep===9)state.finished=true;else state.currentStep++;}return render()}const card=e.target.closest('[data-step]');if(card&&preComplete()){state.finished=false;state.currentStep=Number(card.dataset.step);render();}});document.querySelector('#reset').addEventListener('click',reset);render();}
else module.exports={state,buildTimeline,timingFor,preComplete};
